%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Charis Ellis\Documents\GitHub\Charis_Training_Folder\My_new_array8.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/22 14:47:35

%% Initialize variables.
filename = 'C:\Users\Charis Ellis\Documents\GitHub\Charis_Training_Folder\My_new_array8.dat';
delimiter = ' ';

%% Format for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
Mynewarray1 = table(dataArray{1:end-1}, 'VariableNames', {'Column1','Column2','Column3','Column4'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;